services:
    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.50.0
        container_name: cadvisor
        privileged: true
        devices:
          - /dev/kmsg:/dev/kmsg
        volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:ro
          - /sys:/sys:ro
          - /var/lib/docker:/var/lib/docker:ro
          - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
        restart: unless-stopped
        networks:
          proxy:
        labels:
          - "org.label-schema.group=monitoring"
          - "traefik.enable=true"
          - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
