services:
  dockge:
    image: louislam/dockge:1
    container_name: dockge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /root/project:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    restart: unless-stopped
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.entrypoints=http"
      - "traefik.http.routers.dockge.rule=Host(`dockge.URL`)"
      - "traefik.http.middlewares.dockge-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dockge.middlewares=dockge-https-redirect"
      - "traefik.http.routers.dockge-secure.entrypoints=https"
      - "traefik.http.routers.dockge-secure.rule=Host(`dockge.URL`)"
      - "traefik.http.routers.dockge-secure.tls=true"
      - "traefik.http.routers.dockge-secure.service=dockge"
      - "traefik.http.services.dockge.loadbalancer.server.port=5001"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true