services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:v2.4.7
    container_name: 3x-ui
    hostname: 3x.URL
    volumes:
      - ./conf/config.json:/app/bin/config.json
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      TZ: "UTC"
    tty: true
    networks:
      proxy:
    restart: unless-stopped
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.3x.entrypoints=http"
      - "traefik.http.routers.3x.rule=Host(`3x.URL`)"
      - "traefik.http.middlewares.3x-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.3x.middlewares=3x-https-redirect"
      - "traefik.http.routers.3x-secure.entrypoints=https"
      - "traefik.http.routers.3x-secure.rule=Host(`3x.URL`)"
      - "traefik.http.routers.3x-secure.tls=true"
      - "traefik.http.routers.3x-secure.service=3x"
      - "traefik.http.services.3x.loadbalancer.server.port=2053"

      - "traefik.http.routers.3x-sub.rule=Host(`3x.URL`) && PathPrefix(`/sub`)"
      - "traefik.http.middlewares.3x-sub-mw-strip.stripprefix.prefixes=/sub"
      - "traefik.http.middlewares.3x-sub-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.3x-sub.middlewares=3x-sub-https-redirect"
      - "traefik.http.routers.3x-sub-secure.entrypoints=https"
      - "traefik.http.routers.3x-sub-secure.rule=Host(`3x.URL`) && PathPrefix(`/sub`)"
      - "traefik.http.middlewares.3x-sub-secure-mw-strip.stripprefix.prefixes=/sub"
      - "traefik.http.routers.3x-sub-secure.tls=true"
      - "traefik.http.routers.3x-sub-secure.service=3x-sub"
      - "traefik.http.services.3x-sub.loadbalancer.server.port=2096"

      - "traefik.tcp.routers.xui-proxy.entrypoints=https"
      - "traefik.tcp.routers.xui-proxy.rule=HostSNI(`HOST_SNI`)"
      - "traefik.tcp.routers.xui-proxy.tls=true"
      - "traefik.tcp.routers.xui-proxy.tls.passthrough=true"
      - "traefik.tcp.routers.xui-proxy.service=xui-proxy"
      - "traefik.tcp.services.xui-proxy.loadbalancer.server.port=443"

      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true